steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/sparkonk8/gcloud', '-f', 'Dockerfile', '.']

# Simple sanity check: invoke the new gcloud container to confirm that it was
# built correctly.
- name: 'gcr.io/sparkonk8/gcloud'
  args: ['info']

# Invoke a command that requires auth, to check that it gets piped through
# correctly.
- name: 'gcr.io/sparkonk8/gcloud'
  args: ['source', 'repos', 'clone', 'default']

images:
- 'gcr.io/sparkonk8/gcloud'
